name: Build & Test
run-name: Build & Test

on:
  workflow_run:
    workflows: ["Flake8 Lint"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 3.0
          - 3.1
          - 3.2
          - 3.3
          - 3.4
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - 3.10
          - 3.11
          - 3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install build

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run pytest
        run: |
          python -m pytest tests/test.py

      - name: Run build
        run: |
          python -m build
